/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ClientDetails from "../components/ClientDetails";
import ServiceItemsList from "../components/ServiceItemsList";
import ServiceTime from "../components/ServiceTime";

export interface ReservationData {
	clientDetails: {
		id: string;
		email: string;
		name: string;
		phone: string;
		memberShipCode: string;
		memberShipYear: string;
		reciteNumber: string;
		reciteDate: string;
		note: string;
	};
	serviceType: string;
	serviceDate: string;
	serviceTime: string;
	error: string;
}

const Home: NextPage = () => {
	const [formState, setFormState] = useState<ReservationData>({
		clientDetails: {
			id: "",
			email: "",
			name: "",
			phone: "",
			memberShipCode: "",
			memberShipYear: "",
			reciteNumber: "",
			reciteDate: "",
			note: "",
		},
		serviceType: "",
		serviceDate: "",
		serviceTime: "",
		error: "",
	});

	const onSubmit = () => {
		alert(JSON.stringify(formState, null, 2));
	};
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<img src="/headerImage.png" alt="mainImage" />
				<div className="md:px-16 px-4 py-8">
					<ServiceItemsList formState={formState} setFormState={setFormState} />
					<ServiceTime formState={formState} setFormState={setFormState} />
					<ClientDetails formState={formState} setFormState={setFormState} />
					<div className="w-full flex justify-center my-16">
						<button
							className="shadow-xl rounded-xl bg-yellow-500 w-64 p-2"
							onClick={() => onSubmit()}
						>
							Save
						</button>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
